
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package analizadorfunciones.cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int X = 3;
  public static final int POTENCIA = 7;
  public static final int SUMA = 5;
  public static final int ENTERO = 9;
  public static final int ERROR = 8;
  public static final int EOF = 0;
  public static final int IGUAL = 4;
  public static final int error = 1;
  public static final int FUNCION = 2;
  public static final int RESTA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUNCION",
  "X",
  "IGUAL",
  "SUMA",
  "RESTA",
  "POTENCIA",
  "ERROR",
  "ENTERO"
  };
}

